DATA:
  DIM: 2                  # data dimension
  BATCH_SIZE: 32 #32 for 256, 8 for 512
  TEST_BATCH_SIZE: 16 #128 #16
  DATA_PATH: './data/usgs/waterlines/train_data_g256_update'
#   './data/usgs/waterlines/train_data_g256_update'
#   './data/darpa/scarp_lines/train_data_g256_noprune'
#   './data/darpa/thrust_fault_lines/train_data_g256_noprune' 
#   '/data/weiweidu/relationformer_connection/data/usgs/waterlines/train_data_g256_update' 
#   '/data/weiweidu/relationformer_connection_copy/data/usgs/railroads/train_data_g256_update/'
  TEST_MAP_PATH: '/data/weiweidu/data/USGS_data/CO_Louisville_1965/CO_Louisville_1965_degeo.png'
#   '/data/weiweidu/data/USGS_data/CO_Louisville_1965/CO_Louisville_1965_degeo.png'
#   '/data/weiweidu//data/training_png_shp/CO_BigCostilla.png'
#   '/data/weiweidu/data/USGS_data/CA_Bray_2001/CA_Bray_100414_2001_24000_geo.png'
#    '/data/weiweidu/data/USGS_data/CO_Louisville_1965/CO_Louisville_1965_degeo.png'
  TEST_TIF_PATH: '/data/weiweidu/data/USGS_data/CO_Louisville_1965/CO_Louisville_450543_1965_24000_geo.tif'
  TEST_DATA_PATH:  '/data/weiweidu/relationformer_connection/data/usgs/waterlines/test_bray_data_g256/'
#   './data/usgs/waterlines/test_bray_data_g256/'
#    '/data/weiweidu/relationformer_connection/data/usgs/railroads/test_bray_data_g256/'
#   './data/usgs/railroads/test_data_g256_bray_subregion'
#   '/data/weiweidu/relationformer_connection/data/usgs/waterlines/test_bray_data_g256/'
#   '/data/weiweidu/relationformer_map/data/usgs/louisville_railroads/test_data_g256/' # including all patches
#   './data/darpa/thrust_fault_lines/test_data_g512_AK_HinesCreek'
#   '/data/weiweidu/relationformer_connection/data/usgs/waterlines/test_louisville_data_g256/'
#   '/data/weiweidu/relationformer_connection/data/usgs/railroads/test_louisville_data_g256/'
  PRED_MAP_NAME: 'CO_Louisville_1965_waterlines_pred'
#   'CO_BigCostilla_scarp_lines_pred'
#   'CA_Bray_2001_railroads_pred'
#   'CO_Louisville_1965_waterlines_pred'
  SHP_SAVE_PATH: '' 
  DATASET: 'US20-road-network-2D'     # Dataset name
  IMG_SIZE:  [256, 256]   #[256, 256]    # Input image size
  NUM_WORKERS: 1          # Number of data loading threads
  SEED: 10                # random seed for reproducibility

MODEL:
  NUM_CLASSES: 2          # Number of classes, overwritten in data preparation

  ENCODER:
    TYPE: deformable_transformer_backbone
    NAME: deformable_transformer_backbone
    HIDDEN_DIM: 512 #128 #256 #768
    POSITION_EMBEDDING: sine
    LR_BACKBONE: 5e-6
    NUM_FEATURE_LEVELS: 4
    BACKBONE: resnet101
    MASKS: False
    DILATION: False

    # parameters used else where
    IN_CHANS: 3
    DEPTHS: [4, 4, 8, 8, 18]

  DECODER:
    TYPE: deformable_transformer
    NAME: deformable_transformer
    HIDDEN_DIM: 512 #128 #256 #768
    NHEADS: 8
    ENC_LAYERS: 4 #4 #2
    DEC_LAYERS: 4 #4 #2
    DIM_FEEDFORWARD: 1024 #128 #512 #2048
    DROPOUT: 0.1  # 0.0
    ACTIVATION: relu  
    NUM_FEATURE_LEVELS: 4
    DEC_N_POINTS: 4
    ENC_N_POINTS: 4
    TWO_STAGE: False
    # NUM_QUERIES: 21
    AUX_LOSS: False
    WITH_BOX_REFINE: False
    # RLN_TOKEN: True

    OBJ_TOKEN: 60 #110(thrust), 40(rr, scarp), 60(wt), 280 (thrust512_update), 170(thrust512_prune)
    RLN_TOKEN: 1
    CONN_TOKEN: 1
    DUMMY_TOKEN: 1

    RLN_ATTN: True # only do comb RLN_ATTN True + RLN_TOKEN 0 and reverse

  MATCHER:
    C_CLASS: 3
    C_NODE: 5

TRAIN:
  EPOCHS: 200
  LR: 1e-4
  LR_BACKBONE: 1e-4
  WEIGHT_DECAY: 1e-4
  LR_DROP: 80
  CLIP_MAX_NORM: 0.1  # hardcoded

  SAVE_PATH: "./trained_weights/"          # save path for the checkpoint, log and val results
  VAL_INTERVAL: 400                  # validation interval
  SAVE_VAL: False                   # save validation data

  # loss weight
  LOSSES: ['class', 'nodes', 'edges', 'conns'] #
  W_BBOX: 2.0
  W_CLASS: 3.0 # {3.0, 5.0}
  W_CARD: 1.0
  W_NODE: 5.0 # {5.0, 8.0}
  W_EDGE: 4.0 # {4.0, 5.0}
  W_CONN: 1.0


log:
  exp_name: 'waterlines_update_label_token60_distConn3_adjLoss20'
  message: "Baseline 2D relationformer for 2D sat network"
